<template>
    <div class="cm-page zodiac-game">
        <div class="page-content">
            <div class="panel session-panel">
                <div class="nav-block">
                    <span class="cm-btn btn exit-btn">退出房间</span>
                    <span class="cm-btn btn home-btn">高级房</span>
                </div>
                <div class="block result-block">
                    <div class="block-hd"><p class="title">战绩专区</p></div>
                    <div class="block-bd">
                        <div class="host-item">
                            本轮擂主：旗木卡卡西
                        </div>
                        <ul class="session-list">
                            <li>
                                <span class="label">第一局</span>
                                <div class="result">凤凰，丑牛，地</div>
                                <p class="score">个人战绩：+1234567</p>
                            </li>
                            <li>
                                <span class="label">第一局</span>
                                <div class="result">凤凰，丑牛，地</div>
                                <p class="score">个人战绩：+1234567</p>
                            </li>
                            <li>
                                <span class="label">第一局</span>
                                <div class="result">凤凰，丑牛，地</div>
                                <p class="score">个人战绩：+1234567</p>
                            </li>
                            <li>
                                <span class="label">第一局</span>
                                <div class="result">凤凰，丑牛，地</div>
                                <p class="score">个人战绩：+1234567</p>
                            </li>
                            <li>
                                <span class="label">第一局</span>
                                <div class="result">凤凰，丑牛，地</div>
                                <p class="score">个人战绩：+1234567</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel turntable-panel">
                <div class="table-block">
                    <div class="block-bd">
                        <div class="layers">
                            <div class="line"></div>
                            <div class="line line-2"></div>
                            <div class="line line-3"></div>
                            <div class="line line-4"></div>
                            <div class="line line-5"></div>
                            <div class="line line-6"></div>
                            <div class="outside-layer">
                                <div class="layer-bd">
                                    <div class="item item-1 current">
                                       <div class="item-content">
                                           <div class="current-mask"></div>
                                           <i class="point"></i>
                                           <i class="icon mouse-icon"></i>
                                       </div>
                                    </div>
                                    <div class="item item-2">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon cow-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-3">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon tiger-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-4">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon rabbit-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-5">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon dragon-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-6">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon snake-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-7">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon horse-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-8">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon sheep-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-9">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon monkey-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-10">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon chicken-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-11">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon dog-icon"></i>
                                        </div>
                                    </div>
                                    <div class="item item-12">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon pig-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="middle-layer">
                                <div class="layer-bd">
                                    <div class="item item-1 current">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon turtle-icon"></i>
                                            <span class="name">神龟</span>
                                        </div>
                                    </div>
                                    <div class="item item-2">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon kirin-icon"></i>
                                            <span class="name">麒麟</span>
                                        </div>
                                    </div>
                                    <div class="item item-3">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon phoenix-icon"></i>
                                            <span class="name">凤凰</span>
                                        </div>
                                    </div>
                                    <div class="item item-4">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <i class="point"></i>
                                            <i class="icon pixiu-icon"></i>
                                            <span class="name">貔貅</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="inside-layer">
                                <div class="layer-bd">
                                    <div class="item item-1 current">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-2">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-3">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-4">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-5">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-6">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-7">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-8">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-9">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-10">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-11">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">乾</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                    <div class="item item-12">
                                        <div class="item-content">
                                            <div class="current-mask"></div>
                                            <span class="name">坤</span>
                                            <i class="point"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="timer-layer">
                                <div>
                                    <p class="index">第三局</p>
                                    <p class="time">20s</p>
                                </div>
                            </div>
                            <div class="result-layer">
                                <div class="layer-bd">
                                    <i class="icon radiation-icon"></i>
                                    <i class="icon fuzzy-icon"></i>
                                    <i class="icon zodiac-icon dragon-icon"></i>
                                    <div class="result-items">
                                        <div class="item middle-result-item">
                                            <i class="icon turtle-min-icon"></i>
                                            <span class="name">神龟</span>
                                        </div>
                                        <div class="item outside-result-item">
                                            <span class="name">戍狗</span>
                                        </div>
                                        <div class="item inside-result-item">
                                            <span class="name">坤</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="handle-btn-list">
                    <span class="cm-btn handle-btn apply-btn">申请成为擂主</span>
                    <span class="cm-btn handle-btn entrance-btn">我的农场</span>
                </div>
            </div>
            <div class="panel bet-panel">
                <div class="block bet-block">
                    <div class="block-hd"><p class="title">竞猜区</p></div>
                    <div class="block-bd">
                        <div class="balance">琅琊豆余额:245454543</div>
                        <ul class="choice-list">
                            <li class="cm-btn selected">1K</li>
                            <li class="cm-btn">2K</li>
                            <li class="cm-btn">5K</li>
                            <li class="cm-btn">1W</li>
                            <li class="cm-btn">2W</li>
                            <li class="cm-btn">5W</li>
                        </ul>
                        <div class="area options-area">
                            <div class="area-hd">
                                <span class="title">-&nbsp;竞猜&nbsp;-</span>
                            </div>
                            <div class="area-bd">
                                <ul class="item-list">
                                    <li v-for="(item,index) in optionsList" :key="index" class="item" :class="item.type">
                                        <i class="icon" :class="item.icon"></i>
                                        <div class="item-hd">
                                            <span class="name">{{item.name}}</span>
                                        </div>
                                        <div class="item-bd">
                                            <p>竞猜率:{{item.rate}}%</p>
                                            <p>竞猜额度:{{item.count}}</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel data-panel">
                <div class="block player-block">
                    <div class="block-hd">
                        <table>
                            <thead>
                            <tr>
                                <td class="name">昵称</td>
                                <td class="level">等级</td>
                                <td class="count">战绩</td>
                                <td class="balance">余额</td>
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="block-bd">
                        <table>
                            <tbody>
                            <tr v-for="(item,index) in 10" :key="index">
                                <td class="name">消失的眼泪</td>
                                <td class="level">勇士</td>
                                <td class="count"><span class="win">0胜</span><span class="gap">/</span><span class="lose">2负</span></td>
                                <td class="balance">18k</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="block host-block">
                    <div class="block-hd"><span class="title">擂主后选区</span></div>
                    <div class="block-bd">
                        <table>
                            <tbody>
                            <tr v-for="(item,index) in 10" :key="index">
                                <td class="index">{{index+1}}</td>
                                <td class="name">旗木卡卡西</td>
                                <td class="count"><span class="win">0胜</span><span class="gap">/</span><span class="lose">2负</span></td>
                                <td class="balance">18k</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="block personal-block">
                    <div class="block-hd"><span class="title">个人战绩</span></div>
                    <div class="block-bd">
                        <p>参与局数：3</p>
                        <p>房内战绩：23234234</p>
                        <p>单局最大胜利：6</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style lang="less" rel="stylesheet/less">

</style>
<script>
    import Vue from 'vue'
    import 'swiper/dist/css/swiper.css'

    import { swiper, swiperSlide } from 'vue-awesome-swiper'

    export default {
        components:{
            swiper,
            swiperSlide
        },
        data: function(){
            return {
                optionsList:[
                    {
                        name:'亥猪',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'pig-icon',
                    },
                    {
                        name:'子鼠',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'mouse-icon',
                    },
                    {
                        name:'丑牛',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'cow-icon',
                    },
                    {
                        name:'寅虎',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'tiger-icon',
                    },
                    {
                        name:'卯兔',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'rabbit-icon',
                    },
                    {
                        name:'辰龙',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'dragon-icon',
                    },
                    {
                        name:'巳蛇',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'snake-icon',
                    },
                    {
                        name:'午马',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'horse-icon',
                    },
                    {
                        name:'未羊',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'sheep-icon',
                    },
                    {
                        name:'申猴',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'monkey-icon',
                    },
                    {
                        name:'酉鸡',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'chicken-icon',
                    },
                    {
                        name:'戍狗',
                        rate:26,
                        count:32,
                        type:'outside',
                        icon:'dog-icon',
                    },
                    {
                        name:'神龟',
                        rate:26,
                        count:32,
                        type:'middle',
                        icon:'turtle-icon',
                    },
                    {
                        name:'麒麟',
                        rate:26,
                        count:32,
                        type:'middle',
                        icon:'kirin-icon',
                    },
                    {
                        name:'凤凰',
                        rate:26,
                        count:32,
                        type:'middle',
                        icon:'phoenix-icon',
                    },
                    {
                        name:'貔貅',
                        rate:26,
                        count:32,
                        type:'middle',
                        icon:'pixiu-icon',
                    },
                    {
                        name:'乾',
                        rate:26,
                        count:32,
                        type:'inside',
                    },
                    {
                        name:'坤',
                        rate:26,
                        count:32,
                        type:'inside',
                    },
                ]
            }
        },
        methods: {

        },
        mounted () {

        },
        beforeRouteLeave(to,from,next){
            next();
        },
    }
</script>
